# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
# SPDX-License-Identifier: MIT

storage lfs:
    provider="lfs",
    repo_url="https://gitlab.transnetbw.com/planet-esm/oet/data/oet-repo-i-data",
    local_repo="../../input-data/oet-repo-i-data",
    token_envvar="GITLAB_ACCESS_TOKEN",


rule all:
    input:
        "results/costs_2030.csv",
        "results/eez.zip",


rule get_eez:
    input:
        storage(
            "lfs://f0b1b18/eez/v12_20231025/World_EEZ_v12_20231025_LR.zip"
        ),
    output:
        "results/eez.zip",
    shell:
        "mv {input} {output}"


rule get_costs:
    input:
        storage("lfs://f0b1b18/costs/v0.10.1/costs_2030.csv"),
    output:
        "results/costs_2030.csv",
    shell:
        "mv {input} {output}"
